### ISSUE TITLE
HEX doesn't work when rendering an icon

### ISSUE THREAD

**Issue by Mostik** [levovix0/siwin#1]
RGB work
```nim
  var icon = newImage(32, 32)
  let i = render icon
  i.clear color(255,255,32)
  win.icon = icon
```
HEX doesn't work
```nim
  var icon = newImage(32, 32)
  let i = render icon
  i.clear color(0xFFFF20)
  win.icon = icon
```

**Comment by levovix0** [comment]
При переводе из HEX в цвет следует учитывать прозрачность, в случае 0xFFFF20 цвет будет (r: 255, g: 255, b: 32, a: 0), то есть полностью прозрачный.
чтобы цвет не был прозрачным, надо указать 0x**FF**FFFF20.

**Comment by levovix0** [comment]
добавил функцию времени компиляции для задания цвета из hex.
```nim
color"FFFF20" # -> color(255, 255, 32, 255)
```
